### ISSUE TITLE
MySQL的Images表的desc字段导致的语法错误

### ISSUE THREAD

**Issue by JJLAAA** [DvcLAB/dockerhub#10]
- 使用batchUpsert API出现异常，使用insert API 没有出现异常

**Comment by Scisaga** [comment]
images表desc字段与SQL保留字有潜在冲突，改为description

**Comment by JJLAAA** [comment]
batchUpsert API使用了字符串拼接SQL语句，可尝试使用`desc`解决

**Comment by Scisaga** [comment]
> batchUpsert API使用了字符串拼接SQL语句，可尝试使用`desc`解决

common项目更新了Model.getInsertFields()方法，对`desc`字段进行了额外处理
更新依赖到`one.rewind:raw-data:2.0.9.13`再测试一下 @JJLAAA

**Comment by JJLAAA** [comment]
已解决
