### ISSUE TITLE
镜像列表页创建时间与更新时间问题

### ISSUE THREAD

**Issue by zmh530** [DvcLAB/dockerhub#102]
## 问题
镜像文件创建时间会与更新时间同步刷新
![image](https://user-images.githubusercontent.com/78414223/125403055-a891a580-e3e7-11eb-8db9-c92dbf765b52.png)

**Comment by youzi1030** [comment]
### 问题分析
将post请求的请求体的JSON数据进行反序列化为Image类的对象时，若请求体中没有create_time参数，create_time会被初始化为当前时间，并被更新。（Image继承ModelD，ModelD继承Model，Model将create_time初始化为当前时间）
```
Image obj = JSON.fromJson(source, Image.class);
```

### 解决方法
1. 前端在传参时，可以在请求体中将create_time传回，如下：
```
{
    "uid":"xxx",
    "name":"mysql",
    "tags":[mysql],
    "libs":{"mysql":"2021.8.21"},
    "cover_img_url":"",
    "desc":"mysql数据库镜像test",
    "id":"xxxxx",
    "create_time":"1630138009000"
}
```
