### ISSUE TITLE
一个Container的状态一直为NEW---运行逻辑的验证

### ISSUE THREAD

**Issue by JJLAAA** [DvcLAB/dockerhub#11]
用户关闭容器后（Deleted），没有实际上关闭容器服务，一直使用Kafka发送消息，导致容器状态一直为Keep_Alive

**Comment by Scisaga** [comment]
状态一直为New == 从未收到并处理来自容器的状态更新消息，这肯定不正常，先尝试解决这个问题

**Comment by JJLAAA** [comment]
1. Kafka消费端接受消息后，过滤掉状态为`Deleted`的容器的信息
