### ISSUE TITLE
redis序列化后带引号导致解析错误

### ISSUE THREAD

**Issue by JJLAAA** [DvcLAB/dockerhub#12]
![image](https://user-images.githubusercontent.com/47405525/111957238-b06ec680-8b26-11eb-9d20-3e8da3f8814c.png)

**Comment by JJLAAA** [comment]
包含删除的时候

**Comment by Scisaga** [comment]
没太理解，给出具体代码位置或测试用例 @JJLAAA

**Comment by JJLAAA** [comment]
补充：
    问题位置： 本项目的`com.dvclab.dockerhub.service.ReverseProxyService`92行
```java
```

**Comment by JJLAAA** [comment]
lua脚本解决

**Comment by JJLAAA** [comment]
解决
