### ISSUE TITLE
镜像列表接口用户信息

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/dockerhub#13]
`GET /images`

问题：镜像信息中未包含用户信息。

期望：镜像信息中应包含用户信息。

@Scisaga @JJLAAA

**Comment by JJLAAA** [comment]
镜像是否存在用户--不理解，当前镜像是我们提供的公共产品，何来镜像用户的说法，待讨论

**Comment by JJLAAA** [comment]
更新认领
