### ISSUE TITLE
项目与镜像关联

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/dockerhub#14]
期望：创建容器时可以基于项目的配置文件（dependencies里的依赖包名称+版本号）匹配镜像，提高项目运行成功率。

**Comment by JJLAAA** [comment]
1. 配置文件 @linstein
2. 中台解析配置文件存DB
3. 镜像的依赖查询

**Comment by JJLAAA** [comment]
设计配置文件结构

**Comment by Scisaga** [comment]
> 设计配置文件结构
> 
> ```json
> [
> {
>   "package_name":  ${package_name},
>   "package_version": ${package_version}
> },
> {
>   "package_name":  ${package_name},
>   "package_version": ${package_version}
> }
> ]
> ```

可行方案建议

1. 项目中增加：
```config/dep.conf```
```
[
  { "name":  ${name}, "ver": ${ver}}, ...
]
```
2. ```Image.tags``` 类型改为 Map<String, String>
3. ImageRoute 添加查询接口，输入项目ID，输出可用镜像列表

**Comment by JJLAAA** [comment]
- [版本格式参考](https://github.com/zafarkhaja/jsemver)
