### ISSUE TITLE
PsiAI前端请求接口问题

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/dockerhub#18]
## 问题

1. `GET /project_info` 请求失败
    - 失败原因：用于爬取github阿里云服务器被关闭

## 期望

1. 阿里云服务器重新买一个新的国外服务器
2. `GET /project_info`请求成功时，可以返回一个`code`作为判断标识
3. `GET /datasets_info`请求成功时，可以返回一个`code`作为判断标识

@JJLAAA

**Comment by JJLAAA** [comment]
fixed in commit 747af4a28613baa226528713c4d240df74ccd749
