### ISSUE TITLE
项目列表接口和详情接口中返回cover_img_url

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/dockerhub#29]
1. 项目的配置文件夹中添加头图，路径：config/.cover_img.png，png格式，推荐大小1024*1024 @linstein 
2. 编码：添加项目时，更新项目的cover_img_url信息
3. 测试接口是否能正确返回头图信息

**Comment by Scisaga** [comment]
已完成编码，并提交：https://github.com/DvcLAB/dockerhub/commit/8f0c46cdc8f99f9b820daff036393561c5ee186d
烦请部署测试 @JJLAAA @goodmornight

**Comment by JJLAAA** [comment]
测试成功 @Scisaga，关闭issue
