### ISSUE TITLE
证书网盘归纳整理

### ISSUE THREAD

**Issue by JJLAAA** [DvcLAB/dockerhub#42]
- dev组
- 烦请 @linstein 创建一个nextcloud的资源共享组
[资源位置](http://dvclab.com:60011/apps/files/?dir=/&fileid=2127)

**Comment by linstein** [comment]
可以设置资源共享，方法如下：
1. 点击共享
2. 输入dev，点击添加该分组
![image](https://user-images.githubusercontent.com/38755884/114672794-1b7f7780-9d38-11eb-8b90-98bab0cdd1ef.png)

**Comment by JJLAAA** [comment]
Thx!
