### ISSUE TITLE
运行容器接口问题

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/dockerhub#43]
## 问题
` POST /containers/:id/run`接口
现该接口中需要传gpu_enabled参数
该设置是使用原来创建容器配置好的，还是管理员可以另外在容器列表中设置？
这块接口设计是否有冲突？

**Comment by JJLAAA** [comment]
1. container加入字段gpu_enabled表示是否需要GPU环境
2. 运行容器接口不再提供gpu_enabled参数
