### ISSUE TITLE
增加容器暂停和重新启动接口

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/dockerhub#48]
为前端实现相关功能 @Scisaga

**Comment by JJLAAA** [comment]
已实现相关接口
POST /containers/:id/pause
POST /containers/:id/restart

底层命令还需测试 @goodmornight

**Comment by JJLAAA** [comment]
API 测试通过，等待前端测试验收 @goodmornight

**Comment by goodmornight** [comment]
已测试，接口没有问题。
