### ISSUE TITLE
整理数据集相关API

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/dockerhub#50]
1. 数据集相关API
2. 容器中挂载数据集鉴权讨论 @linstein

**Comment by JJLAAA** [comment]
- 将当前已经部署的API更新到整理文档的v1.1 tab
- 拆分数据集部分到v1.2 tab

**Comment by JJLAAA** [comment]
分为以下几类
0. 关注、收藏等功能暂做备份后期实现
1. 用户与数据集的基本信息交互，包括用户角色与权限的设定
2. 文件的上传与下载（S3）
3. 标注与git版本管理（bucket的挂载与gitServlet的git操作）
