### ISSUE TITLE
已删除的容器CPU和MEM使用率问题

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/dockerhub#53]
## 问题
已删除的容器CPU和MEM使用率是否应该设置为0
![image](https://user-images.githubusercontent.com/17687454/114881079-3f74b300-9e35-11eb-96f4-b588eb12b2ea.png)

## 期望
已删除的容器CPU和MEM使用率设置为0

**Comment by JJLAAA** [comment]
## 修改方式
- 在删除容器时清除其用量信息
