### ISSUE TITLE
多开容器时出现冲突

### ISSUE THREAD

**Issue by JJLAAA** [DvcLAB/dockerhub#58]
## 问题描述
- 测试API时发现，同一台服务器部署第二个容器时，第一个会莫名消失
## 测试方式
- 下载两份不同ID的容器yaml脚本，并按次序运行，脚本A运行完毕后，正常提供服务，此时运行脚本B，第一个脚本立即关闭
<img width="663" alt="截屏2021-04-20 下午10 52 50" src="https://user-images.githubusercontent.com/47405525/115553373-ecd94200-a2df-11eb-9f7a-9e9ba2ca6504.png">

- 上图为脚本B执行时的截图，Recreating后边的ID是第一个脚本对应的ID， Attaching to后边的是第二个脚本对应的ID

- 烦请测试修改 @linstein

**Comment by linstein** [comment]
这不是个bug，是docker-compose的特性。docker-compose会认为在同一文件夹下的具有相同服务的docker-compose文件对应启动一个容器。有如下两种解决方法：
1. 通过加入 -p 参数给容器一个project_name可以在不影响当前容器的情况下启动新的容器，例如` docker-compose -f xxx.yaml -p abc up`
2. 将docker-compose文件放在不同的文件夹下，即可解决此问题。

参考：[have multiple docker-compose.yml files in the same directory with the same service names in them](https://github.com/docker/compose/issues/7403)

**Comment by JJLAAA** [comment]
Thx.
另补充：启动时指定project参数，后续的删除、重启、暂停，都要指定此参数

**Comment by JJLAAA** [comment]
在 69c4b5c5cedc849f9657dc9e7 中解决
