### ISSUE TITLE
添加项目时实现私有pypi服务（bandersnatch）的依赖库动态更新

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/dockerhub#85]
- [x] 1. 添加项目时，可读取项目pypi依赖信息，并实现私有pypi服务（bandersnatch）的依赖库动态更新
- [x] 2. 更新默认juputerlab配置文件
- [x] 3. 功能测试 @JJLAAA

**Comment by JJLAAA** [comment]
测试成功，新的修改为 d7938c0b7b275d08df634337fc81b27ff2b2f9cd

**Comment by JJLAAA** [comment]
需要更新 https://reid.red:233/rewind/common/issues/55 @Scisaga
