### ISSUE TITLE
服务器时间设置

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/dockerhub#91]
更新所有服务器时区设置，并同步时间

**Comment by JJLAAA** [comment]
- 完成
- 参考
   - [如何在Ubuntu20.04上设置或更改时区](https://www.myfreax.com/how-to-set-or-change-timezone-on-ubuntu-20-04/)
   - [如何在Ubuntu上设置时间同步](https://juejin.cn/post/6844903918170800141)
